#!/bin/bash
# shellcheck disable=SC2039
# Purpose:     This script attempts to generate random integers through any means necessary
#              Not to be used for any cryptography, it just generates random integers, that's all!
# Author:      Rawiri Blundell
# Copyright:   (c) 2016 - Beerware As-Is.  
#              No warranty or liability, but some attribution would be nice if it works well
#              for you or you derive your own code.  Just as I've attributed inspiration below.
# Date:        20160222
# Interpreter: This may have a bash shebang, but should work fine in any POSIX compatible shell
#              #!/usr/bin/env ksh or #!/bin/ksh will probably get you working on almost anything
###############################################################################
# Inspiration taken from:
# Colin Riddel provided the perl one liner that started this
# 'rand' by Heiner Steven:
# http://www.shelldorado.com/scripts/cmds/rand
# 'rand' by Malte Skoruppa:
# http://unix.stackexchange.com/questions/157250/how-to-efficiently-generate-large-uniformly-distributed-random-integers-in-bas
# 'randbits' by Gene Spafford:
# http://www.diablotin.com/librairie/networking/puis/ch23_09.htm
###############################################################################
# Set the default variable states
nMin=1
debug=false
nCount=1
repeat=false
zeroPad=false
tmpDir=/tmp/rand

# Simple 'die' function
die() {
  printf '%s\n' "$@" 1>&2
  exit 1
}

# In case we actually use $tmpDir, let's trap and delete it
trap 'rm -rf "${tmpDir}"' EXIT INT TERM HUP

# Figure out our default nMax, working our way back from 2^63-1 to 2^15-1
for maxRand in \
9223372036854775807 4611686018427387903 2305843009213693951 1152921504606846975 \
576460752303423487 288230376151711743 144115188075855871 72057594037927935 \
36028797018963967 18014398509481983 9007199254740991 4503599627370495 \
2251799813685247 1125899906842623 562949953421311 281474976710655 140737488355327 \
70368744177663 35184372088831 17592186044415 8796093022207 4398046511103 \
2199023255551 1099511627775 549755813887 274877906943 137438953471 68719476735 \
34359738367 17179869183 8589934591 4294967295 2147483647 1073741823 536870911 \
268435455 134217727 67108863 33554431 16777215 8388607 4194303 2097151 1048575 \
524287 262143 131071 65535 32767; do
  if [ 1 -ge "${maxRand}" ]; then
    :
  else
    break
  fi
done

# Getopts
while getopts ":dDhm:M:N:rz" Flags; do
  case "${Flags}" in
    (d)   debug="true";;
    (D)   debug="true"; set -x;;
    (h)   printf '%s\n' "" "rand - generate random positive integers" \
            "" "Optional Arguments:" \
            "-d [debug.  Tells you which processing method is used (Default:off)]" \
            "-h [help]" \
            "-m [minimum number (Default:${nMin})]" \
            "-M [maximum number (Default:${maxRand})]" \
            "-N [count.  Number of numbers (Default:${nCount})]" \
            "-r [repeat.  Output lines may be repeated (Default:off)]" \
            "-z [zero pad single digits.  E.g. '9' becomes '09' (Default:off)]" ""
          exit 0;;
    (m)   case "${OPTARG}" in
            (*[!0-9]*|'') die "[ERROR] rand: (-m) '${OPTARG}' is not a number";;
            (*)           nMin="${OPTARG}";;
          esac;;
    (M)   case "${OPTARG}" in
            (*[!0-9]*|'') die "[ERROR] rand: (-M) '${OPTARG}' is not a number";;
            (*)           nMax="${OPTARG}";;
          esac;;
    (N)   case "${OPTARG}" in
            (*[!0-9]*|'') die "[ERROR] rand: (-N) '${OPTARG}' is not a number";;
            (*)           nCount="${OPTARG}";;
          esac;;
    (r)   repeat=true;;
    (z)   zeroPad=true;;
    (\?)  die "[ERROR] rand: Invalid option: '-$OPTARG'.  Try 'rand -h' for usage.";;
    (:)   die "[ERROR] rand: Option '-$OPTARG' requires an argument. e.g. '-$OPTARG 10'";;
  esac
done

# Easter Egg
if printf '%d\n' "${nMax}" 2>&1 | grep -E "out of range|too large" >/dev/null 2>&1; then
  die "[INFO] rand: Come on now, stop being silly." \
    "My upper boundary is *sometimes* '${maxRand}'."
fi

# Double check that we haven't done something silly like have nMax less than nMin
if [ "${nMin}" -ge "${nMax}" ]; then
  die "[ERROR] rand: (-m) minimum value is greater than or equal to (-M) maximum value"
fi

# If repeat is not set, then nCount cannot be higher than nMax
if [ "${repeat}" = "false" ] && [ "${nCount}" -gt "${nMax}" ]; then
  printf '%s\n' "[INFO] rand: Count (${nCount}) cannot be higher than the maximum boundary (${nMax}).  Count will be: ${nMax}."
  nCount="${nMax}"
fi

# Put these vars into the environment so we can import them to perl etc
export nMin nMax nCount

################################################################################
# Functions
################################################################################
# This function simply outputs the method used for random integer generation
Fn_debug() {
  [ "${debug}" = true ] && printf '%s\n' "[DEBUG] rand: Method used is '$*'"
}

# Function to generate a reliable seed for whatever method requires one
# Because 'date +%s' isn't entirely portable, we try other methods to get the epoch
Fn_getSeed() {
  # First we check if /dev/urandom is available.
  # We used to have a method_urandom.  /dev/urandom can generate numbers fast
  # But selecting numbers in ranges etc made for a fairly slow method
  if [ -c /dev/urandom ] && command -v od >/dev/null 2>&1; then
    # Get a string of bytes from /dev/urandom using od
    od -N 4 -A n -t uL /dev/urandom | tr -d " "
  # Otherwise we try to get another seed
  elif date '+%s' >/dev/null 2>&1; then
    date '+%s'
  elif command -v perl >/dev/null 2>&1; then
    perl -e "print time"
  elif command -v truss >/dev/null 2>&1 && [ "$(uname)" = SunOS ]; then
    truss date 2>&1 | grep ^time | awk -F"= " '{print $2}'
  elif command -v truss >/dev/null 2>&1 && [ "$(uname)" = FreeBSD ]; then
    truss date 2>&1 | grep ^gettimeofday | cut -d "{" -f2 | cut -d "." -f1
  # Otherwise, just pump out the raw date
  else
    date '+%Y%M%d%H%M%S'
  fi
}

# This function ensures equal distribution for methods that don't support it
# If you request random numbers between 1 and 10, you should only get a complete
# set of random numbers between 1 and 10.  This is disabled with '-r'
# Note: for POSIX compat, we sadly can't use arrays
# this means there will be potentially a massive performance hit at scale
Fn_fill() {

  # Call the method specified upon function invocation
  # Use Fn_unique to get an unsorted list of unique integers
  intFill=$($1 | Fn_unique)

  # Count how many unique integers we have generated
  intCount=$(printf '%s\n' "${intFill}" | wc -l)

  # If we've generated enough to satisfy nCount, then we just print them out
  if [ "${intCount}" -ge "${nCount}" ]; then
    printf '%s\n' "${intFill}" | head -n "${nCount}"
    
  # Otherwise, we walk through a few steps to try and quickly fill the gap
  else
    # Create a tmpdir
    mkdir -p "${tmpDir}"
    
    # Now dump what we have to a temporary file
    printf '%s\n' "${intFill}" > "${tmpDir}"/rnginit

    # Until we have our full set of random integers,
    # Keep throwing random ints into the temporary file
    while [ "${intCount}" -lt "${nCount}" ]; do
      eval "$1" >> "${tmpDir}"/rnginit
      intCount=$(Fn_unique < "${tmpDir}"/rnginit | wc -l)
    done 

    # Now that the full integer set is built, dump it out
    Fn_unique < "${tmpDir}"/rnginit | head -n "${nCount}"
  fi
}

# Switch between Fn_fill or not
Fn_repeat() {
  if [ "${repeat}" = true ]; then
    "$1"
  else
    Fn_fill "$1"
  fi
}

# This function allows us to print out unsorted, unique integers
Fn_unique() {
  # If 'awk' is available, we use it
  if command -v awk >/dev/null 2>&1; then
    awk '!x[$0]++'
  # Otherwise we use a double sort.  This can be brutally slow at scale.
  # We first prepend each line with a line number, then perform a unique sort
  # on the second field (i.e. the generated integers), then we sort again on the
  # line numbers to return the randomness and use cut to print out the integers
  else
    nl | sort -k 2 -u | sort | cut -f2
  fi
}

# Setup the zeropad function
if [ "${zeroPad}" = true ]; then
  Fn_zeropad() {
    # It appears that 'awk' is more portable vs sed 's/\<[0-9]\>/0&/'
    if command -v awk >/dev/null 2>&1; then
      awk '{$1 = sprintf("%02d", $1); print}'
    else
      die "[ERROR] rand: 'awk' is required for zero-padding but was not found."
    fi
  }
else
  Fn_zeropad() { 
    cat -
  }
fi

# Function to generate numbers using 'gawk'
method_gawk() {
  gawk -v min="${nMin}" -v max="${nMax}" -v nNum="${nCount}" 'BEGIN{srand(systime() + PROCINFO["pid"]); i = 0; while (i < nNum) { printf "%d\n", int(min+rand()*(max-min)); ++i} }'
}

# Function to generate numbers using BSD 'jot'
method_jot() {
  # Some versions of 'jot' have uniform distribution, others do not.
  # This is a lo-fi approach to try and cater for both
  jot -w %i -r "${nCount}" "${nMin}" "$(( nMax + 1 ))" | sed "s/$(( nMax + 1 ))/$(( nMax ))/"
}

# Function to generate numbers using 'nawk'
# This used to also call 'mawk' but that was found to be vulnerable to repeating output
method_nawk() {
  nawk -v min="${nMin}" -v max="${nMax}" -v nNum="${nCount}" -v seed="$(Fn_getSeed)" 'BEGIN {srand(seed); i = 0; while (i < nNum) { printf "%d\n", int(min+rand()*(max-min)); ++i} }'
}

# Function to generate numbers using 'perl'
method_perl() {
  perl -le '$mn=$ENV{nMin}; $mx=$ENV{nMax}; $cn=$ENV{nCount}; foreach my $i (1..$cn) { printf "%.0f\n", int(rand($mx-$mn))+$mn ; }'
}

# Function to generate numbers using 'python'
method_python() {
  python -c "for _ in xrange(${nCount}): import random; print random.randint(${nMin},${nMax})"
  
  # The alternative method below was tested but abandoned for now
  # It fails with a Memory Error if nMax is too high
  # I'll leave it here for prosperity though (note: it may require nMax = nMax + 1)
  #python -c "import random; numlist=list(range(${nMin},${nMax})); random.shuffle(numlist); print '\n'.join([str(int) for int in numlist])"
}

# Function to generate numbers primarily using '$RANDOM' special variable
# If the special variable isn't available (e.g. dash shell), we fall back to a BSD-style
# Linear congruential generator (LCG) which we use to create our own '$RANDOM' variable
# This way, the entire bitshifting formula remains the same
# See: https://rosettacode.org/wiki/Linear_congruential_generator
method_RANDOM() {
  # We need to know the number of bits required to represent nMax (i.e. bitlength)
  # This is for the rightwards bitshift
  logn=1
  nBitlen=0
  while [ $((nMax - nMin)) -gt "${logn}" ] && [ "${logn}" -gt 0 ]; do
    logn=$(( logn * 2 ))
    nBitlen=$(( nBitlen + 1 ))
  done

  # We set the initial seed just in case we're using the LCG
  rnSeed=$(Fn_getSeed)

  # Start a loop based on nCount.  I thought of other ways, but this works easier
  # and can be made more portable if testing proves the need to do so
  while [ "${nCount}" -gt 0 ]; do
    # Start generating seeds for the LCG
    rnSeed=$(( (1103515245 * rnSeed + 12345) % 2147483648 ))
    # If the RANDOM variable is blank, we failover to the LCG
    # We print as an unsigned integer to ensure that it's a positive number
    # shellcheck disable=SC2169
    RANDOM="${RANDOM:-$(printf '%u\n' "$(( rnSeed / 65536 ))")}"
    # Set our initial bitlength
    rndBitlen=15
    # shellcheck disable=SC2169
    rnd="${RANDOM}" # Capture one output sample of RANDOM

    while [ "${rndBitlen}" -lt "${nBitlen}" ]; do
      # Stir the seed again just in case
      rnSeed=$(( (1103515245 * rnSeed + 12345) % 2147483648 ))
      # If two invocations of RANDOM are the same, then we're working with a
      # shell that does not support $RANDOM.  So we use the LCG and rotate $RANDOM
      # shellcheck disable=SC2169
      if [ "${RANDOM}" = "${RANDOM}" ]; then
        RANDOM=$(printf '%u\n' "$(( rnSeed / 65536 ))")
      fi
      # Bitshift RANDOM to the left to stack it i.e. 15 int -> 30 int -> 45 int etc
      # shellcheck disable=SC2169
      rnd=$(( rnd<<15|RANDOM ))
      # Keep stacking until the while loop exits
      rndBitlen=$(( rndBitlen + 15 ))
    done
    # Now bitshift it right
    nRandShift=$(( rnd>>(rndBitlen-nBitlen) ))

    # Next we test if the number we've generated fits into our range.  If so,
    # then we can use it and iterate the while loop
    if [ $((nRandShift + nMin)) -le "${nMax}" ]; then
      printf '%u\n' "$(( nRandShift + nMin ))"
      nCount=$(( nCount - 1 ))
    fi
  done
}

# Function to generate numbers using GNU 'shuf'
method_shuf() {
  # It turns out that Solaris 11 comes with 'shuf' v8.16, which lacks the 
  # '-r' option.  This option was introduced in v8.22
  # Once again, Solaris proves to be the bane of my scripting existence.  

  # First we test if the repeat option has been set, as this requires special handling
  if [ "${repeat}" = true ]; then
    # Test if 'shuf' can use '-r' and if so, use it
    if shuf -n 1 -r -i 1-10 >/dev/null 2>&1; then
      shuf -n "${nCount}" -r -i "${nMin}"-"${nMax}"

    # Otherwise we assume that '-r' isn't available, and do it the old fashioned way
    else
      while [ "${nCount}" -gt 0 ]; do
        shuf -n 1 -i "${nMin}"-"${nMax}"
        # Decrement the counter
        nCount=$(( nCount - 1 ))
      done
    fi
  # If repeat isn't true, just do this
  else
    shuf -n "${nCount}" -i "${nMin}"-"${nMax}"
  fi
}

# Function to attempt random integer generation using a basic-ish Marsaglia xorshift
# This function also attempts to independently handle modulo de-biasing
##############################################
# Currently in testing!  Feedback appreciated!
##############################################
method_xorshift() {
  # Figure out the triples required for the xorshift generator
  # 8 bit and 16 bit triples sourced from
  # http://www.arklyffe.com/main/2010/08/29/xorshift-pseudorandom-number-generator/
  if [ "${nMax}" -ge 255 ]; then
    # 8 bit (1 - 255 )
    shifta=7
    shiftb=5
    shiftc=3
  elif [ "${nMax}" -le 65535 ]; then
    # 16 bit (1 - 65535)
    shifta=13
    shiftb=9
    shiftc=7
  elif [ "${nMax}" -le 4294967295 ]; then
    # 32 bit (1 - 4294967295)
    shifta=13
    shiftb=17
    shiftc=5
  else
    # 63 bit (1 - 9223372036854775807)
    shifta=13
    shiftb=7
    shiftc=17
  fi

  # In order to enable modulo debiasing, we figure out the number of problematic integers 
  # that we need to skip in order to bring plain old modulo usage back into uniform alignment
  # This is massively faster than naive rejection sampling
  # Credit where it is due:
  # http://funloop.org/post/2015-02-27-removing-modulo-bias-redux.html
  # https://blog.hartwork.org/?p=2900
  # This calculation is careful to not invoke negative integer overflow
  skipInts=$(( ((maxRand % nMax) + 1) % nMax ))

  # Grab our initial integer from Fn_getSeed to feed to the RNG
  int=$(Fn_getSeed)

  # Start our count loop
  while [ "${nCount}" -gt 0 ]; do
    # xorshift with preselected triples
    int=$(( int ^ int << shifta ))
    int=$(( int ^ int >> shiftb ))
    int=$(( int ^ int << shiftc ))
     
     # If our generated int is larger than the number of problematic ints
     # Then we can modulo it safely, otherwise drop it and generate again
     # By virtue of skipInts being >= 0, this will also drop generated negative overflow ints
     if [ "${int}" -gt "${skipInts}" ]; then
      printf '%u\n' "$(( (int % nMax) + 1 ))"
      nCount=$(( nCount - 1 ))
    fi
  done
}

# Check if 'seq' is available, if not, provide a basic replacement function
# Note: this has been stripped back to cater only for ascending sequences
# A fuller, bash-friendly version is available at https://github.com/rawiriblundell
if ! command -v seq >/dev/null 2>&1; then
  seq() {
    i=$1
    while [ "$i" -ne "$(( $2 + 1 ))" ]; do
      printf '%s\n' "$i"
      i=$(( i + 1 ))
    done
  }
fi

###############################################################################
# Main
###############################################################################
# Cater for GNU shuf, nice and fast
# This function will also cater for the repeat option natively
if command -v shuf > /dev/null 2>&1; then
  Fn_debug shuf
  method_shuf

# If we're on a BSD based host, likely 'jot' is available, so let's use it
# 'jot' is limited to 2^31-1 by the arc4random algorithm
# so we also test for an nMax limit based on that
elif command -v jot > /dev/null 2>&1 && [ "${nMax}" -lt 2147483647 ]; then
  Fn_debug jot
  # Repeating generated numbers is the default behaviour of 'jot'
  Fn_repeat method_jot

# Now we start going less-native and try perl.  Very likely to be there,   
# so very likely this will be a commonly used option
elif command -v perl > /dev/null 2>&1; then
  Fn_debug perl
  Fn_repeat method_perl

# Otherwise, we try python
# We need to ensure that /dev/urandom is available, as python sources it
elif command -v python > /dev/null 2>&1 && [ -c /dev/urandom ]; then
  Fn_debug python
  Fn_repeat method_python

# No perl or python?  Let's try 'gawk'
elif command -v gawk > /dev/null 2>&1; then
  Fn_debug gawk
  Fn_repeat method_python
  
# No gawk?  Surely 'nawk' is hanging around?  Works very similar, but 
# because we don't have systime() we have to replicate it as a seed for srand().
elif command -v nawk > /dev/null 2>&1; then
  Fn_debug nawk
  Fn_repeat method_nawk

# Note: oawk does not have srand() or rand(), it's more trouble than it's worth so let's move on

# No shuf, jot, perl, python, gawk or nawk?  Fear not!  
# Let's try for a POSIX friendly shell solution.  This is limited to 2^60-1
elif [ "${nMax}" -lt 1152921504606846975 ]; then
  Fn_debug Skoruppa Bitshift
  Fn_repeat method_RANDOM
  
# Provide an outright failure condition just in case
else
  die "[ERROR] rand: Unable to find a suitable method to generate a random integer"
fi | Fn_zeropad

exit 0
